### ISSUE TITLE
Tournament of Teams Actions

### ISSUE THREAD

**Issue by jenpeabody** [OfficeDev/microsoft-teams-apps-tournament-of-teams#5]
When I enter actions for a new tournament into the Actions list, I put them in somewhat of a sequential order. The first few times I created tournaments then, the actions were in the same order as when I added them to the list. However, subsequent attempts have randomly moved the actions around and now they do not make any sense. Why would that be? Is there any way to ensure the actions are kept in a certain order?  I was all ready to launch this to my company when I realized this happened now I am dead in the water until I can figure this out 😕

**Comment by jenpeabody** [comment]
Apologies for not being clear. They are in order in the SharePoint list and also when I am creating a new tournament.  They go out of order when I make the tournament live.  I am attaching some examples to better help explain :)
[Action list items.docx](https://github.com/OfficeDev/microsoft-teams-apps-tournament-of-teams/files/8893109/Action.list.items.docx)

**Comment by v-saikirang** [comment]
Thanks for the details. Please allow us some time. We will get back to you on this ASAP.
Thanks.

**Comment by v-saikirang** [comment]
Hi @jenpeabody,

"Create Tournaments" screen is pulling the data from Actions list.
"My DashBoard" screen is getting the data from "Tournament Actions" list. 
So the Actions in these screens is based on the order of the items in the respective lists. 
The data is being populated to "Tournament Actions" dynamically when a new tournament is created through "Create Tournaments" screen. And we are currently not controlling the order of the items creation since this is an asynchronous operation to avoid performance issues. We will look in to any options to handle this this scenario and try to implement in our future releases. Please let us know if you need more information.

Thanks for your feedback.

**Comment by jenpeabody** [comment]
Thank you for your response! Now that I know where the data is coming from, I was able to clean up the "Tournament Actions" list and all is good ;)
